In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

# Sample data
data_array = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0], [9, 10, 1], [11, 12, 0]])

# Split the data using train_test_split
features = data_array[:, :-1]
labels = data_array[:, -1]
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

# Print the results
print('X_train:')
print(X_train)
print('\ny_train:')
print(y_train)
print('\nX_test:')
print(X_test)
print('\ny_test:')
print(y_test)


X_train:
[[11 12]
 [ 5  6]
 [ 9 10]
 [ 7  8]]

y_train:
[0 1 1 0]

X_test:
[[1 2]
 [3 4]]

y_test:
[0 1]


In [2]:
import numpy as np

# Sample data
data_array = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0]])

# Shuffle the data randomly
np.random.shuffle(data_array)

# Define the split fraction
split_fraction = 0.8
split_index = int(split_fraction * len(data_array))

# Split the data into training and testing sets
X_train = data_array[:split_index, :-1]
y_train = data_array[:split_index, -1]
X_test = data_array[split_index:, :-1]
y_test = data_array[split_index:, -1]

print('X_train:')
print(X_train)
print('\ny_train:')
print(y_train)
print('\nX_test:')
print(X_test)
print('\ny_test:')
print(y_test)


X_train:
[[5 6]
 [7 8]
 [3 4]]

y_train:
[1 0 1]

X_test:
[[1 2]]

y_test:
[0]


In [3]:
import numpy as np

def custom_random_split(input_features, input_labels, split_fraction):
    num_samples = input_features.shape[0]

    # Shuffle the indices randomly
    shuffled_indices = np.random.permutation(num_samples)

    # Calculate the split index
    split_index = int(split_fraction * num_samples)

    # Select the first 'split_index' shuffled indices for training
    train_indices = shuffled_indices[:split_index]

    # Use the selected indices to split the data
    X_train = input_features[train_indices]
    y_train = input_labels[train_indices]

    # The rest of the indices are for testing
    test_indices = shuffled_indices[split_index:]

    X_test = input_features[test_indices]
    y_test = input_labels[test_indices]

    return (X_train, y_train, X_test, y_test)

# Sample data
data_array = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0]])

# Split the data using custom_random_split
X_train, y_train, X_test, y_test = custom_random_split(data_array[:, :-1], data_array[:, -1], split_fraction=0.8)

# Print the results
print('X_train:')
print(X_train)
print('\ny_train:')
print(y_train)
print('\nX_test:')
print(X_test)
print('\ny_test:')
print(y_test)


X_train:
[[7 8]
 [3 4]
 [1 2]]

y_train:
[0 1 0]

X_test:
[[5 6]]

y_test:
[1]


In [4]:
import numpy as np

# Sample data
data_array = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0]])

# Define the split fraction
split_fraction = 0.8

# Calculate the split index
split_index = int(split_fraction * len(data_array))

# Split the data into training and testing sets
X_train = data_array[:split_index, :-1]
y_train = data_array[:split_index, -1]
X_test = data_array[split_index:, :-1]
y_test = data_array[split_index:, -1]

# Print the results
print('X_train:')
print(X_train)
print('\ny_train:')
print(y_train)
print('\nX_test:')
print(X_test)
print('\ny_test:')
print(y_test)


X_train:
[[1 2]
 [3 4]
 [5 6]]

y_train:
[0 1 1]

X_test:
[[7 8]]

y_test:
[0]


In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

# Sample data
data_array = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0]])

# Split the data using train_test_split
features = data_array[:, :-1]
labels = data_array[:, -1]
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

# Print the results
print('X_train:')
print(X_train)
print('\ny_train:')
print(y_train)
print('\nX_test:')
print(X_test)
print('\ny_test:')
print(y_test)


X_train:
[[7 8]
 [1 2]
 [5 6]]

y_train:
[0 0 1]

X_test:
[[3 4]]

y_test:
[1]


In [7]:
import numpy as np

class CustomKNN:
    def __init__(self, n_neighbors=5):
        self.n_neighbors = n_neighbors
        self.X_train = None
        self.y_train = None

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        y_pred = np.zeros(X_test.shape[0])

        for i, x in enumerate(X_test):
            # Calculate distances between the current sample and all training samples
            distances = np.linalg.norm(self.X_train - x, axis=1)

            # Get indices of the k-nearest neighbors
            k_indices = np.argsort(distances)[:self.n_neighbors]

            # Find the most common class label among the neighbors
            neighbor_labels = self.y_train[k_indices]
            unique_labels, label_counts = np.unique(neighbor_labels, return_counts=True)
            y_pred[i] = unique_labels[np.argmax(label_counts)]

        return y_pred


In [8]:
import numpy as np

# Create an instance of the CustomKNN class with default settings (5 neighbors)
custom_knn = CustomKNN()

# Define your training data and labels (example data)
X_train = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y_train = np.array([0, 1, 0, 1])

# Fit the CustomKNN model with the training data and labels
custom_knn.fit(X_train, y_train)


In [9]:
import numpy as np
from sklearn.metrics import accuracy_score

# Define the CustomKNN class
class CustomKNN:
    def __init__(self, n_neighbors=5):
        self.n_neighbors = n_neighbors
        self.X_train = None
        self.y_train = None

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        y_pred = np.zeros(X_test.shape[0])

        for i, x in enumerate(X_test):
            # Calculate distances between the current sample and all training samples
            distances = np.linalg.norm(self.X_train - x, axis=1)

            # Get indices of the k-nearest neighbors
            k_indices = np.argsort(distances)[:self.n_neighbors]

            # Find the most common class label among the neighbors
            neighbor_labels = self.y_train[k_indices]
            unique_labels, label_counts = np.unique(neighbor_labels, return_counts=True)
            y_pred[i] = unique_labels[np.argmax(label_counts)]

        return y_pred

    def evaluate(self, X_test, y_test):
        # Predict labels for the test data
        y_pred = self.predict(X_test)

        # Calculate accuracy
        accuracy = accuracy_score(y_test, y_pred)

        return accuracy, y_pred

# Create an instance of the CustomKNN class with default settings (5 neighbors)
custom_knn = CustomKNN()

# Define your training data and labels (example data)
X_train = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y_train = np.array([0, 1, 0, 1])

# Fit the CustomKNN model with the training data and labels
custom_knn.fit(X_train, y_train)

# Define your test data and labels (example data)
X_test = np.array([[1.5, 2.5], [3.5, 4.5]])
y_test = np.array([0, 0])

# Evaluate the model and get predictions and accuracy
accuracy, y_pred = custom_knn.evaluate(X_test, y_test)

# Print the results
print("Predictions:", y_pred)
print("Accuracy:", accuracy)


Predictions: [0. 0.]
Accuracy: 1.0


In [10]:
from sklearn.metrics import accuracy_score
import numpy as np

# Sample data (replace with your data)
X_train = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y_train = np.array([0, 1, 0, 1])
X_test = np.array([[2, 2], [3, 3]])
y_true = np.array([0, 1])

# Define a range of hyperparameters to search
n_neighbors_values = [3, 5, 7]
weights_values = ['uniform', 'distance']

best_accuracy = 0
best_params = {}

# Iterate through all hyperparameter combinations
for n_neighbors in n_neighbors_values:
    for weights in weights_values:
        # Create and train a KNN model with the current hyperparameters
        class CustomKNN:
            def __init__(self):
                self.n_neighbors = n_neighbors
                self.weights = weights
                self.X_train = None
                self.y_train = None

            def fit(self, X, y):
                self.X_train = X
                self.y_train = y

            def predict(self, X):
                y_pred = []

                for x in X:
                    # Calculate distances between the current sample and all training samples
                    distances = [np.linalg.norm(x - x_train) for x_train in self.X_train]

                    # Get indices of the k-nearest neighbors
                    k_indices = np.argsort(distances)[:self.n_neighbors]

                    # Find the most common class label among the neighbors
                    neighbor_labels = [self.y_train[i] for i in k_indices]
                    unique_labels, label_counts = np.unique(neighbor_labels, return_counts=True)
                    y_pred.append(unique_labels[np.argmax(label_counts)])

                return np.array(y_pred)

        knn = CustomKNN()
        knn.fit(X_train, y_train)

        # Make predictions on the test set
        y_pred = knn.predict(X_test)

        # Calculate accuracy
        accuracy = accuracy_score(y_true, y_pred)

        # Check if this combination of hyperparameters gives a better accuracy
        if accuracy > best_accuracy:
            best_accuracy = accuracy
            best_params = {'n_neighbors': n_neighbors, 'weights': weights}

print(f"Best Hyperparameters: {best_params}")
print(f"Best Accuracy: {best_accuracy}")


Best Hyperparameters: {'n_neighbors': 3, 'weights': 'uniform'}
Best Accuracy: 0.5
